### ISSUE TITLE
Problem when finetuning few-shot model

### ISSUE THREAD

**Issue by lrakotoarivony** [LiewFeng/imTED#1]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
Apparently, the LayerDecayOptimizerConstructorBackboneFronzen is not in the optimizer builder registry. Where can I find it?

**Reproduction**

I use the following command

```none
python tools/train.py configs/imted/few_shot/imted_faster_rcnn_vit_base_2x_finetuning_10shot_coco.py
```

**Error traceback**

```none
KeyError: 'LayerDecayOptimizerConstructorBackboneFronzen is not in the optimizer builder registry'
```

I tried to search for the LayerDecayOptimizerConstructorBackboneFronzen in the code but I don't find it. Please tell me where can I find the code associated with this layer.

Thanks.

**Comment by LiewFeng** [comment]
Sorry. Code of LayerDecayOptimizerConstructorBackboneFronzen is now updated [here](https://github.com/LiewFeng/imTED/blob/main/mmcv_custom/layer_decay_optimizer_constructor_backbone_frozen.py).
