### ISSUE TITLE
The detection head uses a randomly initialized decoder instead of a decoder using pretrained MAE weights

### ISSUE THREAD

**Issue by luoyq6** [LiewFeng/imTED#10]
Hello, excuse me, do you have a config file that does not use the decoder with MAE pre-trained weights, but uses the decoder with randomly initialized parameters as the detection header

**Comment by LiewFeng** [comment]
Hi, the "random decoder" option is depreacated in our final version of code, you can modify it [here](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/roi_heads/bbox_heads/mae_bbox_head.py#LL71C8-L71C8).

**Comment by LiewFeng** [comment]
Closed due to inactivity. Feel free to reopen it if necessary.
