### ISSUE TITLE
Number of Parameters

### ISSUE THREAD

**Issue by nil123532** [LiewFeng/imTED#12]
Hi, what is the total number of parameters in your models?

**Comment by LiewFeng** [comment]
Hi, the params are listed as follows.

1. imTED+Faster RCNN+ViT-S: 30.3M
2. imTED+Faster RCNN+ViT-B: 123M
3. imTED+Faster RCNN+ViT-L: 346M
4. imTED+Mask RCNN+ViT-S: 32.9M
5. imTED+Mask RCNN+ViT-B: 125M
6. imTED+Mask RCNN+ViT-L: 349M

**Comment by LiewFeng** [comment]
Closed due to inactivity. Feel free to reopen it if necessary.
