### ISSUE TITLE
Evaluation for few-shot object detection

### ISSUE THREAD

**Issue by nil123532** [LiewFeng/imTED#13]
Hi, 
On how many images did you evaluate for novel classes for few-shot object detection on the MS-COCO benchmark (60 base classes and 20 novel classes)? 
And how did you obtain that from this link : http://dl.yf.io/fs-det/datasets/cocosplit/

Best

**Comment by LiewFeng** [comment]
Hi，we use this [json](http://[dl.yf.io/fs-det/datasets/cocosplit/datasplit/trainvalno5k.json](http://dl.yf.io/fs-det/datasets/cocosplit/datasplit/trainvalno5k.json)) fro evaluation. We don't count the number of images. If you're interested, you can check the json mentioned above.

**Comment by nil123532** [comment]
So to evaluate the FSOD 9 seeds you used the trainvalno5k.json?

**Comment by LiewFeng** [comment]
We report the performance of the model trained on seed 0, following previous work. The evaluation is conducted on the trainvalno5k.json.

**Comment by RafLaf** [comment]
Hi @LiewFeng,
Thanks for your answer! May I ask a couple more questions?
    -Is the "seed 0" the list of classes (in several shots settings) that I see when clicking on the link of the original issue post after "seed 9" (see screenshot below)?
    -Could you provide me with a paper that details completely the evaluation protocol. I could not find a proper document that highlights it all! I am particularly interested in knowing how many seeds and which seeds should be used as "few training examples". 
    
Thanks ! 
![image](https://github.com/LiewFeng/imTED/assets/73280556/d49900a9-b134-4ba5-8bd9-e0ea0324787d)

**Comment by LiewFeng** [comment]
@nil123532 Hi, to be more clear, trainvalno5k.json is used to generate the 10/30 shot taining json and  5k.json is for evaluation. We report the performance of novel class.

**Comment by LiewFeng** [comment]
@RafLaf Hi, for the first question, yes. For the second question, you may refer to [link](https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/README.md#:~:text=2%2C%20and%203.-,COCO%3A,-cocosplit/%0A%20%20datasplit/%0A%20%20%20%20trainvalno5k) and [link](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/MODEL_ZOO.md#results-on-seed-0-1). Most of previous work conduct experiments on seed 0 only.

**Comment by RafLaf** [comment]
Thanks!

**Comment by LiewFeng** [comment]
Closed due to inactivity. Feel free to reopen it if necessary.

**Comment by amajee11us** [comment]
Hi, thank you for the response on this thread.
The config file for finetuning accepts only 1 json for train but in the previous posts there are multiple json files for each class.
Can you please let me know the steps how you combined these files ?
