### ISSUE TITLE
Codes for the baseline （ViT based Faster R-CNN）

### ISSUE THREAD

**Issue by lovelyqian** [LiewFeng/imTED#14]
Hi, very thanks for releasing the codes for imTED. 

I am very interested in the comparison between the ViT-based Faster R-CNN and the imTED, however, I did not find the codes for the baseline.  Could you kindly provide the codes related to the baseline e.g., the model and the training? Thanks for your time and consideration!

**Comment by LiewFeng** [comment]
Hi，@lovelyqian, thank you for your interest. We reconstruct our code and the original config of the basline with Faster RCNN + ViT-B is not that compatible with the current code. You may reproduce it by

1. replace the config of [roi_head](https://github.com/LiewFeng/imTED/blob/main/configs/imted/imted_faster_rcnn_vit_base_3x_coco.py#L51C5-L51C13) with the commanly used [StandardROIHead](https://github.com/open-mmlab/mmdetection/blob/v2.10.0/configs/_base_/models/fast_rcnn_r50_fpn.py#L19)
2. replace the config of [bboxhead](https://github.com/LiewFeng/imTED/blob/main/configs/imted/imted_faster_rcnn_vit_base_3x_coco.py#L63) with [ConvFCBBoxHead](https://github.com/open-mmlab/mmdetection/blob/f78af7785ada87f1ced75a2313746e4ba3149760/configs/convnext/cascade-mask-rcnn_convnext-t-p4-w7_fpn_4conv1fc-giou_amp-ms-crop-3x_coco.py#L28)
3. comment [this line](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/detectors/imted.py#L30)
4. set [with_mfm](https://github.com/LiewFeng/imTED/blob/main/configs/imted/imted_faster_rcnn_vit_base_3x_coco.py#L50) as False

**Comment by lovelyqian** [comment]
Hi, @LiewFeng very thanks for your kind reply. I will try it!

**Comment by LiewFeng** [comment]
Closed due to inactivity. Feel free to reopen it if necessary.
