### ISSUE TITLE
question about load checkpoint

### ISSUE THREAD

**Issue by menglongyue** [LiewFeng/imTED#15]
hello, thanks for you excellent work first! i met some question when loading weights, there are so many unexpect keys as below, is this normal?
<img width="1488" alt="image" src="https://github.com/LiewFeng/imTED/assets/45710485/5c541d2f-45ef-4842-80b2-811ad487c756">

**Comment by LiewFeng** [comment]
Hi，@menglongyue，it's normal in the training process. We load the pre-trained weights for encoder and decoder seperately. The unexpected keys in the log are the parameters of the encoder when loading weights for the decoder(MAEBoxHead).

**Comment by menglongyue** [comment]
@LiewFeng Thanks for you reply very much, i understand it now. another place i do not understand, how to devide foreground and background, could you please explain it?
<img width="631" alt="image" src="https://github.com/LiewFeng/imTED/assets/45710485/c1c51767-3ee5-482b-8941-cda2bc614a9a">

**Comment by LiewFeng** [comment]
@menglongyue For the base training of COCO in the few-shot setting, there are only 60 foreground classes and 1 background class, whhile for the finetuing, there are 80 foreground classes and 1 background class. Thus, when loading weights from the checkpoint of base training, we need to move the class weight of background to the last.

**Comment by menglongyue** [comment]
ok, i get it. Thank you very much!

**Comment by menglongyue** [comment]
@LiewFeng ok, i get it. Thank you very much!
