### ISSUE TITLE
mmcv

### ISSUE THREAD

**Issue by chuanchengh** [LiewFeng/imTED#17]
May I ask how many versions of 'mmcv' need to be downloaded? The prompt for me to download 2.0.0 is that I cannot use 'Config' and 'DictAction', as well as' mmcv. parallel 'and' mmcv. runner '

**Comment by LiewFeng** [comment]
You may refer to  [this](https://github.com/LiewFeng/imTED/issues/11#issuecomment-1457407941).

**Comment by chuanchengh** [comment]
Hello, I configured the environment based on your get_started.md file, but the final output always prompts me that mmengine is not imported, or prompts me that mmcv-full has been renamed mmcv. Another prompt is that I The mmcv version is too low (1.7.1), so I was asked to update to 2.0.0 or above, but after I updated, I was prompted that this version cannot import config. This may also be caused by problems with my understanding and operation.
