### ISSUE TITLE
How to fed the roi feature after MFM into MAE decoder？

### ISSUE THREAD

**Issue by Livioni** [LiewFeng/imTED#21]
I am trying to migrate this project (ImTed) to mmdetection3.x. However, I have some doubts about how to send roi features after the _Multi-scale Feature Modulator_ to mae decoder. 
I found that the _bbox_feats_' shape are like torch.Size([512, 384, 7, 7])，but the self.bbox_head, i.e., the mae decoder requires inputs like x.shape = [b_s, dim, W, H], how to solve this?

```python
def _bbox_forward(self, x, rois):
        """Box head forward function used in both training and testing."""
        # TODO: a more flexible way to decide which feature maps to use
        if self.with_mfm:
            ss_bbox_feats = self.ss_bbox_roi_extractor(
                [x[-1]], rois)
            x = [self.mfm_fc(x[i]) for i in range(self.ms_bbox_roi_extractor.num_inputs)]
            ms_bbox_feats = self.ms_bbox_roi_extractor(
                x[:self.ms_bbox_roi_extractor.num_inputs], rois) # multi scale

            factor = self.mfm_factor.reshape(1, -1, 1, 1).expand_as(ms_bbox_feats)
            bbox_feats = ss_bbox_feats + ms_bbox_feats * factor
        else:
            bbox_feats = self.bbox_roi_extractor(
                x[:self.bbox_roi_extractor.num_inputs], rois)
        if self.with_shared_head:
            bbox_feats = self.shared_head(bbox_feats)
        cls_score, bbox_pred = self.bbox_head(bbox_feats)
```

**Comment by LiewFeng** [comment]
Hi, @Livioni , see [here](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/roi_heads/bbox_heads/mae_bbox_head.py#L119)

**Comment by Livioni** [comment]
> Hi, @Livioni , see [here](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/roi_heads/bbox_heads/mae_bbox_head.py#L119)

Thanks for your reply, but _x.flatten(2).transpose(1, 2)_ reshapes [512, 384, 7, 7] into [512,49,384], which is not consistent with the decoder. Decoder requires [batch_size, token_num, embed_dim]. Is there a problem with my understanding？

**Comment by LiewFeng** [comment]
The shape of the output of [modified function](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/roi_heads/imted_roi_head.py#L53) is the same as that of [original function](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/roi_heads/standard_roi_head.py#L133).  The shape of input of  [mae_bbox_head](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/roi_heads/bbox_heads/mae_bbox_head.py#L117) is the same as that of commonly used [convfc_bbox_head](https://github.com/LiewFeng/imTED/blob/main/mmdet/models/roi_heads/bbox_heads/convfc_bbox_head.py#L135). The output of Multi-scale Feature Modulator is what mae_bbox_head needs. The shape matches. Do you encounter any shape problem when migrating code?

**Comment by HappyGoLucky6666** [comment]
Have you successfully replicated the project's results from this paper? I encountered issues while setting up the environment. Could you please share your environment configuration with me? I would appreciate it if you could include detailed version information for all the libraries so that I can run the experiment successfully on my local machine. Thank you.@Livioni
