### ISSUE TITLE
can't open get_started.md 

### ISSUE THREAD

**Issue by renshouyu** [LiewFeng/imTED#23]
请问get_started.md 为什么无法打开啊？

**Comment by LiewFeng** [comment]
更新了链接了，你再试试

**Comment by HappyGoLucky6666** [comment]
请问一下你复现出了这篇文章的项目了吗？我在配置环境的时候出现了问题，能否将你的环境配置内容给我分享一份，里面我希望能够有各种库的详细版本版本信息，以便于我也能在本地跑通实验，谢谢!@renshouyu
