### ISSUE TITLE
Excuse me, are there any test results on the PASCAL VOC dataset?

### ISSUE THREAD

**Issue by luoyq6** [LiewFeng/imTED#3]
Hello, I see that you only tested the effect on coco dataset, have you experimented on PASCAL VOC? Or can you provide the weights you trained on the coco dataset? thank you

**Comment by LiewFeng** [comment]
1. We don't conduct experiments on PASCAL VOC. You can try it.
2. The weights are now updated in the [README](https://github.com/LiewFeng/imTED/blob/main/README.md).
