### ISSUE TITLE
KeyError: 'LayerDecayOptimizerConstructorBackboneFronzen is not in the optimizer builder registry'

### ISSUE THREAD

**Issue by luoyq6** [LiewFeng/imTED#4]
Excuse me, but I got the following error while training with imted_faster_rcnn_vit_base_2x_finetuning_10shot_coco.py. Can you help explain it? thank you
![1671089652991](https://user-images.githubusercontent.com/110521846/207800107-938cb5d6-792c-4d8e-9ddc-7173e8be6fdd.png)
@LiewFeng

**Comment by LiewFeng** [comment]
Fixed in [#1](https://github.com/LiewFeng/imTED/issues/1). The code of LayerDecayOptimizerConstructorBackboneFronzen is updated several dyas ago. Please clone the newest code.
