### ISSUE TITLE
I had some problems visualizing the detection

### ISSUE THREAD

**Issue by luoyq6** [LiewFeng/imTED#6]
Hello, I'm sorry to bother you again. I find that your paper has no visual inspection effect. Have you done anything about that? Or is there a demo

**Comment by LiewFeng** [comment]
Do you mean how to visualize the detection results? If so, [link1](https://github.com/open-mmlab/mmdetection/blob/v2.10.0/docs/useful_tools.md#result-analysis) and [link2](https://github.com/open-mmlab/mmdetection/blob/v2.10.0/docs/useful_tools.md#visualization) may help you.
