### ISSUE TITLE
Weights of ViT-S

### ISSUE THREAD

**Issue by lrakotoarivony** [LiewFeng/imTED#7]
Hello, I am trying to reproduce your work however I can't find the weights for the ViT-S model. The weights for ViT-B and ViT-L are available but not for ViT-S.

Would it be possible to provide a link to download the ViT-S weights?

Thanks

**Comment by LiewFeng** [comment]
Hi, weight is available [here](https://mailsucasaccn-my.sharepoint.com/:u:/g/personal/liufeng20_mails_ucas_ac_cn/ET7GIhcqLY1KlqfsYthBrU4BLf1BwgboqXwTALxdxHKlUA?e=Z7aOuC).

**Comment by lrakotoarivony** [comment]
Thanks. Great work by the way.
