### ISSUE TITLE
I got an error when I used the command to evaluate

### ISSUE THREAD

**Issue by luoyq6** [LiewFeng/imTED#9]
I got an error when I used the command to evaluate bash ./tools/dist_test.sh work_dirs/imted_faster_rcnn_vit_base_2x_finetuning_CID/imted_faster_rcnn_vit_base_2x_finetuning_10shot_coco.py work_dirs/imted_faster_rcnn_vit_base_2x_finetuning_CID/epoch_18.pth 1 --eval bbox
![1673256155745](https://user-images.githubusercontent.com/110521846/211276124-3086ae18-3b05-479d-832e-5b4f73533884.png)

**Comment by LiewFeng** [comment]
Hi. Do you modify the 'pretrained' in the config file? According to the error message, the 'pretrained' is None, which should be the path of pretrained model. Can you check where is the None passed to the init function?

**Comment by luoyq6** [comment]
I have modified the config file, using this file can be trained, but not evaluated
![1673320775533](https://user-images.githubusercontent.com/110521846/211454440-025740ad-c079-4437-8614-4c5ec061401b.png)

**Comment by LiewFeng** [comment]
Sorry. Deleting line 126 in [tools/test.py](https://github.com/LiewFeng/imTED/blob/main/tools/test.py#L126) should work. Code is updated now.

**Comment by luoyq6** [comment]
ok,Thank you. It's ready to work
